#!/bin/bash

TOP=jt12_test
DUMPSIGNALS=DONT
EXTRA=
RANDWAIT=1

while [ $# -gt 0 ]; do
	if [ $1 = "-w" ]; then
		echo "Signal dump enabled"
		DUMPSIGNALS=DUMPSIGNALS
		shift
		continue
	fi   
	if [ $1 = "-norandwait" ]; then
		echo "Random wait disabled"
		RANDWAIT=0
		shift
		continue
	fi     
	#Pass all unrecognized options to inputs.cc
	EXTRA=$EXTRA" "$1
	shift
done

if ! g++ inputs.cc -o inputs; then
	exit 1
fi

#echo $EXTRA
echo Preparing stimuli file
if ! ./inputs $EXTRA > inputs.vh; then
	exit 1
fi
#exit 0

rm -f s

if expr match "$(uname -v)" ".*Ubuntu.*" > /dev/null; then
	echo "LINT check (only DUT files)"
	verilator -f gather_dut.f --lint-only
	# Actual simulation
	echo Simulation start
    iverilog -f gather.f -s $TOP -o sim -I../../hdl -DDISPLAY_STEP \
    	-D$DUMPSIGNALS -DRANDWAIT=$RANDWAIT -DTEST_SUPPORT -DSIMULATION && sim -lxt > s
    #exit 0
    if [ $? -ne 0 ]; then
	    cat s
	    rm s
	    exit 1
    fi	
else
	ncverilog -f gather.f +access+rc +incdir+../../hdl +nctop+$TOP \
    	+define+NCVERILOG+DISPLAY_STEP+$DUMPSIGNALS+TEST_SUPPORT+RANDWAIT=$RANDWAIT \
    	+define+SIMULATION > s
	if [ $? -ne 0 ]; then
		cat s
		rm s
		exit 1
	fi
fi

if grep ERROR s; then
	exit 1;
fi

cat s | awk 'BEGIN{ g=0 }
/DUMP END/ { g=3 }
{ if( g==2 ) print $0 }
/DUMP START/ { if(g<2) g=2 }' | tail -n 24 > output.csv
sort output.csv > output_sorted.csv
sort verify.csv > verify_sorted.csv
diff output_sorted.csv verify_sorted.csv
if [ $? -eq 0 ]; then
	echo TEST PASS
else
	echo TEST FAIL
fi
